name: Yarn install
description: Install and cache dependencies using Yarn
inputs: 
  node-version:
      description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
      default: 'lts/*'
runs:
  using: 'composite'
  steps:
    - name: Fetch repo 🧤
      uses: actions/checkout@v4
      
    - name: Set Node ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock
        
    - name: Install dependencies 📦
      shell: bash
      run: yarn install
